"""change model

Revision ID: 3246351d0337
Revises: a7a827a7e6d3
Create Date: 2020-06-12 09:18:41.374836

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3246351d0337'
down_revision = 'a7a827a7e6d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quizbank', sa.Column('other_answer_1', sa.Text(), nullable=True))
    op.drop_column('quizbank', 'other_answer')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quizbank', sa.Column('other_answer', mysql.TEXT(), nullable=True))
    op.drop_column('quizbank', 'other_answer_1')
    # ### end Alembic commands ###
