"""change model

Revision ID: a7a827a7e6d3
Revises: e5cf3b77d549
Create Date: 2020-06-12 09:18:20.131887

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7a827a7e6d3'
down_revision = 'e5cf3b77d549'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quizbank', sa.Column('other_answer_2', sa.Text(), nullable=True))
    op.add_column('quizbank', sa.Column('other_answer_3', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quizbank', 'other_answer_3')
    op.drop_column('quizbank', 'other_answer_2')
    # ### end Alembic commands ###
